# Generated by Django 4.2.5 on 2023-11-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0045_employee_loan_tran_balance_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_loan_tran',
            name='balance_loan',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeeloan',
            name='balance_loan',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
